// AUTO-GENERATED from live Atlas Cloud model schemas (https://api.atlascloud.ai/api/v1/models +
// https://static.atlascloud.ai/model/schema/*). Verified 2026-06-28. Do not hand-edit; regenerate from
// the schemas. Capabilities (reference-image maxima, source field, mask, custom dimensions, controls,
// price) are derived from each model's documented OpenAPI Input schema, not guessed. See docs/notes/776.
import type { ImageModelDefinition } from './imageProviderCapabilities';

export const ATLAS_GENERATED_IMAGE_MODELS: ImageModelDefinition[] = [
  {
    providerId: 'atlas',
    modelId: 'microsoft/mai-image-2.5-flash/text-to-image',
    label: 'MAI-Image-2.5-Flash Text-to-image',
    recommendedUse: 'MAI-Image-2.5-Flash Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.03, unitLabel: '$0.03/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/microsoft/mai-image-2.5-flash/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'microsoft/mai-image-2.5/edit',
    label: 'MAI-Image-2.5 Edit',
    recommendedUse: 'MAI-Image-2.5 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","textEditPrompt"],
    cost: { imageEditUsd: 0.058, unitLabel: '$0.058/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/microsoft/mai-image-2.5/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'microsoft/mai-image-2.5/text-to-image',
    label: 'MAI-Image-2.5 Text-to-image',
    recommendedUse: 'MAI-Image-2.5 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.05, unitLabel: '$0.05/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/microsoft/mai-image-2.5/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'youchuan/v8.1/remove-background',
    label: 'Youchuan V8.1 Remove Background',
    recommendedUse: 'Youchuan V8.1 Remove Background on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":true,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["remove-background"],
    visibleControls: ["prompt"],
    cost: { imageEditUsd: 0.086, unitLabel: '$0.086/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/youchuan/v8.1/remove-background',
  },
  {
    providerId: 'atlas',
    modelId: 'youchuan/v8.1/style-transfer',
    label: 'Youchuan V8.1 Style Transfer',
    recommendedUse: 'Youchuan V8.1 Style Transfer on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage"],
    cost: { imageEditUsd: 0.129, unitLabel: '$0.129/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/youchuan/v8.1/style-transfer',
  },
  {
    providerId: 'atlas',
    modelId: 'youchuan/v8.1/blend',
    label: 'Youchuan V8.1 Blend',
    recommendedUse: 'Youchuan V8.1 Blend on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":5,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","seed"],
    cost: { imageEditUsd: 0.086, unitLabel: '$0.086/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/youchuan/v8.1/blend',
  },
  {
    providerId: 'atlas',
    modelId: 'youchuan/v8.1/image-to-image',
    label: 'Youchuan V8.1 Image-to-Image',
    recommendedUse: 'Youchuan V8.1 Image-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","seed"],
    cost: { imageEditUsd: 0.086, unitLabel: '$0.086/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/youchuan/v8.1/image-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'youchuan/v8.1/text-to-image',
    label: 'Youchuan V8.1 Text-to-Image',
    recommendedUse: 'Youchuan V8.1 Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed"],
    cost: { textToImageUsd: 0.086, unitLabel: '$0.086/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/youchuan/v8.1/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/reference-to-image',
    label: 'Nano Banana 2 Reference to Image',
    recommendedUse: 'Nano Banana 2 Reference to Image on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.08, unitLabel: '$0.08/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/reference-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/reference-to-image-developer',
    label: 'Nano Banana 2 Reference to Image Developer',
    recommendedUse: 'Nano Banana 2 Reference to Image Developer on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.04, unitLabel: '$0.04/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/reference-to-image-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'xai/grok-imagine-image-quality/text-to-image',
    label: 'Grok Imagine Image Quality Text-to-Image',
    recommendedUse: 'Grok Imagine Image Quality Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio"],
    cost: { textToImageUsd: 0.05, unitLabel: '$0.05/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/xai/grok-imagine-image-quality/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'xai/grok-imagine-image-quality/edit',
    label: 'Grok Imagine Image Quality Edit',
    recommendedUse: 'Grok Imagine Image Quality Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":8,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages"],
    cost: { imageEditUsd: 0.05, unitLabel: '$0.05/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/xai/grok-imagine-image-quality/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-2/text-to-image',
    label: 'Openai GPT Image 2 Text-to-Image',
    recommendedUse: 'Openai GPT Image 2 Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.009, unitLabel: '$0.009/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-2/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-2/edit',
    label: 'Openai GPT Image 2 Edit',
    recommendedUse: 'Openai GPT Image 2 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.01, unitLabel: '$0.01/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-2/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'baidu/ERNIE-Image-Turbo/text-to-image',
    label: 'Baidu ERNIE Image Turbo Text-to-image',
    recommendedUse: 'Baidu ERNIE Image Turbo Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","steps","seed","guidanceScale"],
    cost: { confidence: 'provider-defined', unitLabel: 'provider-billed' },
    docsUrl: 'https://www.atlascloud.ai/models/baidu/ERNIE-Image-Turbo/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.7/text-to-image',
    label: 'Wan-2.7 Text-to-image',
    recommendedUse: 'Wan-2.7 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.03, unitLabel: '$0.03/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.7/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.7/image-edit',
    label: 'Wan-2.7 Image-to-image',
    recommendedUse: 'Wan-2.7 Image-to-image on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":9,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed"],
    cost: { imageEditUsd: 0.03, unitLabel: '$0.03/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.7/image-edit',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.7-pro/text-to-image',
    label: 'Wan-2.7 Pro Text-to-image',
    recommendedUse: 'Wan-2.7 Pro Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.075, unitLabel: '$0.075/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.7-pro/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.7-pro/image-edit',
    label: 'Wan-2.7 Pro Image-to-image',
    recommendedUse: 'Wan-2.7 Pro Image-to-image on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":9,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed"],
    cost: { imageEditUsd: 0.075, unitLabel: '$0.075/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.7-pro/image-edit',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/text-to-image-developer',
    label: 'Nano Banana 2 Text-to-Image Developer',
    recommendedUse: 'Nano Banana 2 Text-to-Image Developer on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio"],
    cost: { textToImageUsd: 0.04, unitLabel: '$0.04/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/text-to-image-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/text-to-image',
    label: 'Nano Banana 2 Text-to-Image',
    recommendedUse: 'Nano Banana 2 Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","outputFormat"],
    cost: { textToImageUsd: 0.08, unitLabel: '$0.08/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/edit-developer',
    label: 'Nano Banana 2 Edit Developer',
    recommendedUse: 'Nano Banana 2 Edit Developer on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":14,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.04, unitLabel: '$0.04/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/edit-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-2/edit',
    label: 'Nano Banana 2 Edit',
    recommendedUse: 'Nano Banana 2 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":14,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.08, unitLabel: '$0.08/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-2/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'qwen/qwen-image-2.0/text-to-image',
    label: 'Qwen Image 2.0 Text-to-image',
    recommendedUse: 'Qwen Image 2.0 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.028, unitLabel: '$0.028/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/qwen/qwen-image-2.0/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'qwen/qwen-image-2.0/edit',
    label: 'Qwen Image 2.0 Edit',
    recommendedUse: 'Qwen Image 2.0 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","textEditPrompt"],
    cost: { imageEditUsd: 0.028, unitLabel: '$0.028/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/qwen/qwen-image-2.0/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'qwen/qwen-image-2.0-pro/edit',
    label: 'Qwen Image 2.0 Pro Edit',
    recommendedUse: 'Qwen Image 2.0 Pro Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","textEditPrompt"],
    cost: { imageEditUsd: 0.06, unitLabel: '$0.06/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/qwen/qwen-image-2.0-pro/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'qwen/qwen-image-2.0-pro/text-to-image',
    label: 'Qwen Image 2.0 Pro Text-to-image',
    recommendedUse: 'Qwen Image 2.0 Pro Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.06, unitLabel: '$0.06/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/qwen/qwen-image-2.0-pro/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v5.0-lite/edit-sequential',
    label: 'Seedream v5.0 Lite Edit Sequential',
    recommendedUse: 'Seedream v5.0 Lite Edit Sequential on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":14,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.032, unitLabel: '$0.032/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v5.0-lite/edit-sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v5.0-lite/sequential',
    label: 'Seedream v5.0 Lite Sequential',
    recommendedUse: 'Seedream v5.0 Lite Sequential on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.032, unitLabel: '$0.032/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v5.0-lite/sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v5.0-lite/edit',
    label: 'Seedream v5.0 Lite Edit',
    recommendedUse: 'Seedream v5.0 Lite Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":14,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.032, unitLabel: '$0.032/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v5.0-lite/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v5.0-lite',
    label: 'Seedream v5.0 Lite',
    recommendedUse: 'Seedream v5.0 Lite on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.032, unitLabel: '$0.032/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v5.0-lite',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1.5/text-to-image',
    label: 'Openai GPT Image-1.5 Text-to-image',
    recommendedUse: 'Openai GPT Image-1.5 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.008, unitLabel: '$0.008/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1.5/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1.5/edit',
    label: 'Openai GPT Image-1.5 Edit',
    recommendedUse: 'Openai GPT Image-1.5 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.008, unitLabel: '$0.008/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1.5/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/qwen-image/edit-plus-20251215',
    label: 'Qwen-Image Edit Plus 20251215',
    recommendedUse: 'Qwen-Image Edit Plus 20251215 on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","negativePrompt","textEditPrompt"],
    cost: { imageEditUsd: 0.021, unitLabel: '$0.021/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/qwen-image/edit-plus-20251215',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.6/image-edit',
    label: 'Wan-2.6 Image-to-image',
    recommendedUse: 'Wan-2.6 Image-to-image on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":4,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","negativePrompt"],
    cost: { imageEditUsd: 0.021, unitLabel: '$0.021/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.6/image-edit',
  },
  {
    providerId: 'atlas',
    modelId: 'z-image/turbo',
    label: 'Z-Image Turbo',
    recommendedUse: 'Z-Image Turbo on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.005, unitLabel: '$0.005/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/z-image/turbo',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1/text-to-image',
    label: 'Openai GPT Image-1 Text-to-image',
    recommendedUse: 'Openai GPT Image-1 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.009, unitLabel: '$0.009/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1/edit',
    label: 'Openai GPT Image-1 Edit',
    recommendedUse: 'Openai GPT Image-1 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":true,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":4,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit","mask-inpaint"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","mask","textEditPrompt"],
    cost: { imageEditUsd: 0.009, unitLabel: '$0.009/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1-mini/text-to-image',
    label: 'Openai GPT Image-1 Mini Text-to-image',
    recommendedUse: 'Openai GPT Image-1 Mini Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.004, unitLabel: '$0.004/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1-mini/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-1-mini/edit',
    label: 'Openai GPT Image-1 Mini Edit',
    recommendedUse: 'Openai GPT Image-1 Mini Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":4,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.004, unitLabel: '$0.004/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-1-mini/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4.5',
    label: 'Seedream v4.5',
    recommendedUse: 'Seedream v4.5 on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.036, unitLabel: '$0.036/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4.5',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4.5/edit',
    label: 'Seedream v4.5 Edit',
    recommendedUse: 'Seedream v4.5 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.036, unitLabel: '$0.036/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4.5/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4.5/sequential',
    label: 'Seedream v4.5 Sequential',
    recommendedUse: 'Seedream v4.5 Sequential on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.036, unitLabel: '$0.036/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4.5/sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4.5/edit-sequential',
    label: 'Seedream v4.5 Edit Sequential',
    recommendedUse: 'Seedream v4.5 Edit Sequential on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.036, unitLabel: '$0.036/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4.5/edit-sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'atlascloud/qwen-image/edit',
    label: 'Qwen Image Edit',
    recommendedUse: 'Qwen Image Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","seed","textEditPrompt"],
    cost: { imageEditUsd: 0.032, unitLabel: '$0.032/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/atlascloud/qwen-image/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/text-to-image-ultra',
    label: 'Nano Banana Pro Text-to-image Ultra',
    recommendedUse: 'Nano Banana Pro Text-to-image Ultra on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","outputFormat"],
    cost: { textToImageUsd: 0.15, unitLabel: '$0.15/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/text-to-image-ultra',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/edit-ultra',
    label: 'Nano Banana Pro Edit Ultra',
    recommendedUse: 'Nano Banana Pro Edit Ultra on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.15, unitLabel: '$0.15/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/edit-ultra',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/text-to-image',
    label: 'Nano Banana Pro Text-to-image',
    recommendedUse: 'Nano Banana Pro Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","outputFormat"],
    cost: { textToImageUsd: 0.14, unitLabel: '$0.14/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/qwen-image/text-to-image-max',
    label: 'Qwen-Image Text-to-image Max',
    recommendedUse: 'Qwen-Image Text-to-image Max on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","negativePrompt"],
    cost: { textToImageUsd: 0.052, unitLabel: '$0.052/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/qwen-image/text-to-image-max',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/qwen-image/text-to-image-plus',
    label: 'Qwen-Image Text-to-image Plus',
    recommendedUse: 'Qwen-Image Text-to-image Plus on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","negativePrompt"],
    cost: { textToImageUsd: 0.021, unitLabel: '$0.021/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/qwen-image/text-to-image-plus',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/edit',
    label: 'Nano Banana Pro Edit',
    recommendedUse: 'Nano Banana Pro Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.14, unitLabel: '$0.14/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'xai/grok-imagine-image/edit',
    label: 'Grok Imagine Image Edit',
    recommendedUse: 'Grok Imagine Image Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":8,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages"],
    cost: { imageEditUsd: 0.02, unitLabel: '$0.02/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/xai/grok-imagine-image/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'xai/grok-imagine-image/text-to-image',
    label: 'Grok Imagine Image Text-to-Image',
    recommendedUse: 'Grok Imagine Image Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio"],
    cost: { textToImageUsd: 0.02, unitLabel: '$0.02/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/xai/grok-imagine-image/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-2-developer/edit',
    label: 'GPT Image 2 Developer Edit',
    recommendedUse: 'GPT Image 2 Developer Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.005, unitLabel: '$0.005/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-2-developer/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.5/image-edit',
    label: 'Wan-2.5 Image Edit',
    recommendedUse: 'Wan-2.5 Image Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","negativePrompt"],
    cost: { imageEditUsd: 0.021, unitLabel: '$0.021/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.5/image-edit',
  },
  {
    providerId: 'atlas',
    modelId: 'openai/gpt-image-2-developer/text-to-image',
    label: 'GPT Image 2 Developer Text-to-Image',
    recommendedUse: 'GPT Image 2 Developer Text-to-Image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","outputFormat"],
    cost: { textToImageUsd: 0.004, unitLabel: '$0.004/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/openai/gpt-image-2-developer/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.5/text-to-image',
    label: 'Wan-2.5 Text-to-image',
    recommendedUse: 'Wan-2.5 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","negativePrompt"],
    cost: { textToImageUsd: 0.021, unitLabel: '$0.021/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.5/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4',
    label: 'Seedream v4',
    recommendedUse: 'Seedream v4 on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.027, unitLabel: '$0.027/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4/sequential',
    label: 'Seedream v4 Sequential',
    recommendedUse: 'Seedream v4 Sequential on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions"],
    cost: { textToImageUsd: 0.027, unitLabel: '$0.027/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4/sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/text-to-image-developer',
    label: 'Nano Banana Pro Text-to-image Developer',
    recommendedUse: 'Nano Banana Pro Text-to-image Developer on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio"],
    cost: { textToImageUsd: 0.07, unitLabel: '$0.07/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/text-to-image-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana/text-to-image-developer',
    label: 'Nano Banana Text-to-image Developer',
    recommendedUse: 'Nano Banana Text-to-image Developer on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio"],
    cost: { textToImageUsd: 0.019, unitLabel: '$0.019/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana/text-to-image-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4/edit',
    label: 'Seedream v4 Edit',
    recommendedUse: 'Seedream v4 Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.027, unitLabel: '$0.027/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/qwen-image/edit',
    label: 'Qwen-Image Edit',
    recommendedUse: 'Qwen-Image Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","referenceImages","seed","negativePrompt","textEditPrompt"],
    cost: { imageEditUsd: 0.032, unitLabel: '$0.032/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/qwen-image/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/qwen-image/edit-plus',
    label: 'Qwen-Image Edit Plus',
    recommendedUse: 'Qwen-Image Edit Plus on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":3,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","negativePrompt","textEditPrompt"],
    cost: { imageEditUsd: 0.021, unitLabel: '$0.021/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/qwen-image/edit-plus',
  },
  {
    providerId: 'atlas',
    modelId: 'alibaba/wan-2.6/text-to-image',
    label: 'Wan-2.6 Text-to-image',
    recommendedUse: 'Wan-2.6 Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","negativePrompt"],
    cost: { textToImageUsd: 0.021, unitLabel: '$0.021/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/alibaba/wan-2.6/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana-pro/edit-developer',
    label: 'Nano Banana Pro Edit Developer',
    recommendedUse: 'Nano Banana Pro Edit Developer on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.07, unitLabel: '$0.07/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana-pro/edit-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana/edit-developer',
    label: 'Nano Banana Edit Developer',
    recommendedUse: 'Nano Banana Edit Developer on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.019, unitLabel: '$0.019/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana/edit-developer',
  },
  {
    providerId: 'atlas',
    modelId: 'bytedance/seedream-v4/edit-sequential',
    label: 'Seedream v4 Edit Sequential',
    recommendedUse: 'Seedream v4 Edit Sequential on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","textEditPrompt"],
    cost: { imageEditUsd: 0.027, unitLabel: '$0.027/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/bytedance/seedream-v4/edit-sequential',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana/text-to-image',
    label: 'Nano Banana Text-to-image',
    recommendedUse: 'Nano Banana Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","outputFormat"],
    cost: { textToImageUsd: 0.038, unitLabel: '$0.038/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/nano-banana/edit',
    label: 'Nano Banana Edit',
    recommendedUse: 'Nano Banana Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":10,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","referenceImages","textEditPrompt","outputFormat"],
    cost: { imageEditUsd: 0.038, unitLabel: '$0.038/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/nano-banana/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'google/imagen3',
    label: 'Imagen3',
    recommendedUse: 'Imagen3 on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed","negativePrompt"],
    cost: { textToImageUsd: 0.04, unitLabel: '$0.04/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/imagen3',
  },
  {
    providerId: 'atlas',
    modelId: 'google/imagen3-fast',
    label: 'Image3 Fast',
    recommendedUse: 'Image3 Fast on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed","negativePrompt"],
    cost: { textToImageUsd: 0.02, unitLabel: '$0.02/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/imagen3-fast',
  },
  {
    providerId: 'atlas',
    modelId: 'atlascloud/qwen-image/text-to-image',
    label: 'Qwen Image Text-to-image',
    recommendedUse: 'Qwen Image Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed"],
    cost: { textToImageUsd: 0.024, unitLabel: '$0.024/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/atlascloud/qwen-image/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'google/imagen4-fast',
    label: 'Imagen4 Fast',
    recommendedUse: 'Imagen4 Fast on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed","negativePrompt"],
    cost: { textToImageUsd: 0.02, unitLabel: '$0.02/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/imagen4-fast',
  },
  {
    providerId: 'atlas',
    modelId: 'atlascloud/image-upscaler',
    label: 'Image Upscaler',
    recommendedUse: 'Image Upscaler on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":true,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["upscale"],
    visibleControls: ["prompt","outputFormat"],
    cost: { imageEditUsd: 0.01, unitLabel: '$0.01/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/atlascloud/image-upscaler',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-dev',
    label: 'Flux Dev',
    recommendedUse: 'Flux Dev on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","steps","seed","guidanceScale","exactColorPrompt","safetyChecker"],
    cost: { textToImageUsd: 0.012, unitLabel: '$0.012/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-dev',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-kontext-dev',
    label: 'Flux Kontext Dev',
    recommendedUse: 'Flux Kontext Dev on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","steps","seed","guidanceScale","textEditPrompt","exactColorPrompt","safetyChecker"],
    cost: { imageEditUsd: 0.025, unitLabel: '$0.025/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-kontext-dev',
  },
  {
    providerId: 'atlas',
    modelId: 'google/imagen4-ultra',
    label: 'Imagen4 Ultra',
    recommendedUse: 'Imagen4 Ultra on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed","negativePrompt"],
    cost: { textToImageUsd: 0.06, unitLabel: '$0.06/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/imagen4-ultra',
  },
  {
    providerId: 'atlas',
    modelId: 'google/imagen4',
    label: 'Imagen4',
    recommendedUse: 'Imagen4 on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","seed","negativePrompt"],
    cost: { textToImageUsd: 0.04, unitLabel: '$0.04/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/google/imagen4',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-kontext-dev-lora',
    label: 'Flux Kontext Dev Lora',
    recommendedUse: 'Flux Kontext Dev Lora on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","steps","seed","guidanceScale","loraWeights","textEditPrompt","exactColorPrompt","outputFormat"],
    cost: { imageEditUsd: 0.03, unitLabel: '$0.03/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-kontext-dev-lora',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-schnell',
    label: 'Flux Schnell',
    recommendedUse: 'Flux Schnell on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","exactColorPrompt","safetyChecker"],
    cost: { textToImageUsd: 0.003, unitLabel: '$0.003/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-schnell',
  },
  {
    providerId: 'atlas',
    modelId: 'microsoft/mai-image-2.5-flash/edit',
    label: 'MAI-Image-2.5-Flash Edit',
    recommendedUse: 'MAI-Image-2.5-Flash Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":false,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":false},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","textEditPrompt"],
    cost: { imageEditUsd: 0.038, unitLabel: '$0.038/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/microsoft/mai-image-2.5-flash/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-2-flex/edit',
    label: 'FLUX.2 Flex Edit',
    recommendedUse: 'FLUX.2 Flex Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":8,"exactColorControl":true,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","steps","seed","guidanceScale","textEditPrompt","exactColorPrompt","safetyChecker","outputFormat"],
    cost: { imageEditUsd: 0.05, unitLabel: '$0.05/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-2-flex/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-2-flex/text-to-image',
    label: 'FLUX.2 Flex Text-to-image',
    recommendedUse: 'FLUX.2 Flex Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","steps","seed","guidanceScale","exactColorPrompt","safetyChecker","outputFormat"],
    cost: { textToImageUsd: 0.05, unitLabel: '$0.05/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-2-flex/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-2-pro/edit',
    label: 'FLUX.2 Pro Edit',
    recommendedUse: 'FLUX.2 Pro Edit on Atlas Cloud.',
    capabilities: {"textToImage":false,"imageToImage":true,"promptEdit":true,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":true,"maxReferenceImages":8,"exactColorControl":true,"typography":true,"textInImageEditing":true,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["image-edit"],
    visibleControls: ["prompt","sourceImage","aspectRatio","dimensions","referenceImages","seed","textEditPrompt","exactColorPrompt","safetyChecker","outputFormat"],
    cost: { imageEditUsd: 0.03, unitLabel: '$0.03/edit', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-2-pro/edit',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-2-pro/text-to-image',
    label: 'FLUX.2 Pro Text-to-image',
    recommendedUse: 'FLUX.2 Pro Text-to-image on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":true,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","exactColorPrompt","safetyChecker","outputFormat"],
    cost: { textToImageUsd: 0.03, unitLabel: '$0.03/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-2-pro/text-to-image',
  },
  {
    providerId: 'atlas',
    modelId: 'black-forest-labs/flux-dev-lora',
    label: 'Flux Dev Lora',
    recommendedUse: 'Flux Dev Lora on Atlas Cloud.',
    capabilities: {"textToImage":true,"imageToImage":false,"promptEdit":false,"maskInpaint":false,"outpaint":false,"erase":false,"searchReplace":false,"searchRecolor":false,"removeBackground":false,"replaceBackgroundRelight":false,"upscale":false,"referenceImages":false,"maxReferenceImages":0,"exactColorControl":true,"typography":false,"textInImageEditing":false,"localEndpoint":false,"customDimensions":true},
    supportedOperations: ["text-to-image"],
    visibleControls: ["prompt","aspectRatio","dimensions","seed","guidanceScale","loraWeights","exactColorPrompt"],
    cost: { textToImageUsd: 0.015, unitLabel: '$0.015/image', confidence: 'published-fixed' },
    docsUrl: 'https://www.atlascloud.ai/models/black-forest-labs/flux-dev-lora',
  },
];
