// AUTO-GENERATED from the live Atlas Cloud image catalog (https://api.atlascloud.ai/api/v1/models,
// verified 2026-06-28). The model picker's Atlas image options. Includes EVERY documented 2D image model
// so every model — and every feature it exposes (references, edit, mask, custom size, …) — is selectable.
// Do not hand-edit; regenerate from the catalog.
import type { SelectOption } from '../types/flow';

export const ATLAS_IMAGE_MODEL_OPTIONS: SelectOption[] = [
  { value: 'alibaba/qwen-image/edit', label: 'Atlas Qwen-Image Edit' },
  { value: 'alibaba/qwen-image/edit-plus', label: 'Atlas Qwen-Image Edit Plus' },
  { value: 'alibaba/qwen-image/edit-plus-20251215', label: 'Atlas Qwen-Image Edit Plus 20251215' },
  { value: 'alibaba/qwen-image/text-to-image-max', label: 'Atlas Qwen-Image Text-to-image Max' },
  { value: 'alibaba/qwen-image/text-to-image-plus', label: 'Atlas Qwen-Image Text-to-image Plus' },
  { value: 'alibaba/wan-2.5/image-edit', label: 'Atlas Wan-2.5 Image Edit' },
  { value: 'alibaba/wan-2.5/text-to-image', label: 'Atlas Wan-2.5 Text-to-image' },
  { value: 'alibaba/wan-2.6/image-edit', label: 'Atlas Wan-2.6 Image-to-image' },
  { value: 'alibaba/wan-2.6/text-to-image', label: 'Atlas Wan-2.6 Text-to-image' },
  { value: 'alibaba/wan-2.7-pro/image-edit', label: 'Atlas Wan-2.7 Pro Image-to-image' },
  { value: 'alibaba/wan-2.7-pro/text-to-image', label: 'Atlas Wan-2.7 Pro Text-to-image' },
  { value: 'alibaba/wan-2.7/image-edit', label: 'Atlas Wan-2.7 Image-to-image' },
  { value: 'alibaba/wan-2.7/text-to-image', label: 'Atlas Wan-2.7 Text-to-image' },
  { value: 'atlascloud/image-upscaler', label: 'Atlas Image Upscaler' },
  { value: 'atlascloud/qwen-image/edit', label: 'Atlas Qwen Image Edit' },
  { value: 'atlascloud/qwen-image/text-to-image', label: 'Atlas Qwen Image Text-to-image' },
  { value: 'baidu/ERNIE-Image-Turbo/text-to-image', label: 'Atlas Baidu ERNIE Image Turbo Text-to-image' },
  { value: 'black-forest-labs/flux-2-flex/edit', label: 'Atlas FLUX.2 Flex Edit' },
  { value: 'black-forest-labs/flux-2-flex/text-to-image', label: 'Atlas FLUX.2 Flex Text-to-image' },
  { value: 'black-forest-labs/flux-2-pro/edit', label: 'Atlas FLUX.2 Pro Edit' },
  { value: 'black-forest-labs/flux-2-pro/text-to-image', label: 'Atlas FLUX.2 Pro Text-to-image' },
  { value: 'black-forest-labs/flux-dev', label: 'Atlas Flux Dev' },
  { value: 'black-forest-labs/flux-dev-lora', label: 'Atlas Flux Dev Lora' },
  { value: 'black-forest-labs/flux-kontext-dev', label: 'Atlas Flux Kontext Dev' },
  { value: 'black-forest-labs/flux-kontext-dev-lora', label: 'Atlas Flux Kontext Dev Lora' },
  { value: 'black-forest-labs/flux-schnell', label: 'Atlas Flux Schnell' },
  { value: 'bytedance/seedream-v4', label: 'Atlas Seedream v4' },
  { value: 'bytedance/seedream-v4.5', label: 'Atlas Seedream v4.5' },
  { value: 'bytedance/seedream-v4.5/edit', label: 'Atlas Seedream v4.5 Edit' },
  { value: 'bytedance/seedream-v4.5/edit-sequential', label: 'Atlas Seedream v4.5 Edit Sequential' },
  { value: 'bytedance/seedream-v4.5/sequential', label: 'Atlas Seedream v4.5 Sequential' },
  { value: 'bytedance/seedream-v4/edit', label: 'Atlas Seedream v4 Edit' },
  { value: 'bytedance/seedream-v4/edit-sequential', label: 'Atlas Seedream v4 Edit Sequential' },
  { value: 'bytedance/seedream-v4/sequential', label: 'Atlas Seedream v4 Sequential' },
  { value: 'bytedance/seedream-v5.0-lite', label: 'Atlas Seedream v5.0 Lite' },
  { value: 'bytedance/seedream-v5.0-lite/edit', label: 'Atlas Seedream v5.0 Lite Edit' },
  { value: 'bytedance/seedream-v5.0-lite/edit-sequential', label: 'Atlas Seedream v5.0 Lite Edit Sequential' },
  { value: 'bytedance/seedream-v5.0-lite/sequential', label: 'Atlas Seedream v5.0 Lite Sequential' },
  { value: 'google/imagen3', label: 'Atlas Imagen3' },
  { value: 'google/imagen3-fast', label: 'Atlas Image3 Fast' },
  { value: 'google/imagen4', label: 'Atlas Imagen4' },
  { value: 'google/imagen4-fast', label: 'Atlas Imagen4 Fast' },
  { value: 'google/imagen4-ultra', label: 'Atlas Imagen4 Ultra' },
  { value: 'google/nano-banana-2/edit', label: 'Atlas Nano Banana 2 Edit' },
  { value: 'google/nano-banana-2/edit-developer', label: 'Atlas Nano Banana 2 Edit Developer' },
  { value: 'google/nano-banana-2/reference-to-image', label: 'Atlas Nano Banana 2 Reference to Image' },
  { value: 'google/nano-banana-2/reference-to-image-developer', label: 'Atlas Nano Banana 2 Reference to Image Developer' },
  { value: 'google/nano-banana-2/text-to-image', label: 'Atlas Nano Banana 2 Text-to-Image' },
  { value: 'google/nano-banana-2/text-to-image-developer', label: 'Atlas Nano Banana 2 Text-to-Image Developer' },
  { value: 'google/nano-banana-pro/edit', label: 'Atlas Nano Banana Pro Edit' },
  { value: 'google/nano-banana-pro/edit-developer', label: 'Atlas Nano Banana Pro Edit Developer' },
  { value: 'google/nano-banana-pro/edit-ultra', label: 'Atlas Nano Banana Pro Edit Ultra' },
  { value: 'google/nano-banana-pro/text-to-image', label: 'Atlas Nano Banana Pro Text-to-image' },
  { value: 'google/nano-banana-pro/text-to-image-developer', label: 'Atlas Nano Banana Pro Text-to-image Developer' },
  { value: 'google/nano-banana-pro/text-to-image-ultra', label: 'Atlas Nano Banana Pro Text-to-image Ultra' },
  { value: 'google/nano-banana/edit', label: 'Atlas Nano Banana Edit' },
  { value: 'google/nano-banana/edit-developer', label: 'Atlas Nano Banana Edit Developer' },
  { value: 'google/nano-banana/text-to-image', label: 'Atlas Nano Banana Text-to-image' },
  { value: 'google/nano-banana/text-to-image-developer', label: 'Atlas Nano Banana Text-to-image Developer' },
  { value: 'microsoft/mai-image-2.5-flash/edit', label: 'Atlas MAI-Image-2.5-Flash Edit' },
  { value: 'microsoft/mai-image-2.5-flash/text-to-image', label: 'Atlas MAI-Image-2.5-Flash Text-to-image' },
  { value: 'microsoft/mai-image-2.5/edit', label: 'Atlas MAI-Image-2.5 Edit' },
  { value: 'microsoft/mai-image-2.5/text-to-image', label: 'Atlas MAI-Image-2.5 Text-to-image' },
  { value: 'openai/gpt-image-1-mini/edit', label: 'Atlas Openai GPT Image-1 Mini Edit' },
  { value: 'openai/gpt-image-1-mini/text-to-image', label: 'Atlas Openai GPT Image-1 Mini Text-to-image' },
  { value: 'openai/gpt-image-1.5/edit', label: 'Atlas Openai GPT Image-1.5 Edit' },
  { value: 'openai/gpt-image-1.5/text-to-image', label: 'Atlas Openai GPT Image-1.5 Text-to-image' },
  { value: 'openai/gpt-image-1/edit', label: 'Atlas Openai GPT Image-1 Edit' },
  { value: 'openai/gpt-image-1/text-to-image', label: 'Atlas Openai GPT Image-1 Text-to-image' },
  { value: 'openai/gpt-image-2-developer/edit', label: 'Atlas GPT Image 2 Developer Edit' },
  { value: 'openai/gpt-image-2-developer/text-to-image', label: 'Atlas GPT Image 2 Developer Text-to-Image' },
  { value: 'openai/gpt-image-2/edit', label: 'Atlas Openai GPT Image 2 Edit' },
  { value: 'openai/gpt-image-2/text-to-image', label: 'Atlas Openai GPT Image 2 Text-to-Image' },
  { value: 'qwen/qwen-image-2.0-pro/edit', label: 'Atlas Qwen Image 2.0 Pro Edit' },
  { value: 'qwen/qwen-image-2.0-pro/text-to-image', label: 'Atlas Qwen Image 2.0 Pro Text-to-image' },
  { value: 'qwen/qwen-image-2.0/edit', label: 'Atlas Qwen Image 2.0 Edit' },
  { value: 'qwen/qwen-image-2.0/text-to-image', label: 'Atlas Qwen Image 2.0 Text-to-image' },
  { value: 'xai/grok-imagine-image-quality/edit', label: 'Atlas Grok Imagine Image Quality Edit' },
  { value: 'xai/grok-imagine-image-quality/text-to-image', label: 'Atlas Grok Imagine Image Quality Text-to-Image' },
  { value: 'xai/grok-imagine-image/edit', label: 'Atlas Grok Imagine Image Edit' },
  { value: 'xai/grok-imagine-image/text-to-image', label: 'Atlas Grok Imagine Image Text-to-Image' },
  { value: 'youchuan/v8.1/blend', label: 'Atlas Youchuan V8.1 Blend' },
  { value: 'youchuan/v8.1/image-to-image', label: 'Atlas Youchuan V8.1 Image-to-Image' },
  { value: 'youchuan/v8.1/remove-background', label: 'Atlas Youchuan V8.1 Remove Background' },
  { value: 'youchuan/v8.1/style-transfer', label: 'Atlas Youchuan V8.1 Style Transfer' },
  { value: 'youchuan/v8.1/text-to-image', label: 'Atlas Youchuan V8.1 Text-to-Image' },
  { value: 'z-image/turbo', label: 'Atlas Z-Image Turbo' },
];
