import { inflateZlibBounded } from './boundedInflate';

const MAGIC = 20000630;
const MAX_PIXELS = 64 * 1024 * 1024;

export interface ExrRaster { width: number; height: number; depth: 'f16' | 'f32'; data: Float32Array; }

/** Bounded single-part, uncompressed scanline EXR RGB[A] codec. EXR samples are premultiplied on disk. */
export function decodeExr(bytes: Uint8Array): ExrRaster {
  if (bytes.length < 12) throw new Error('EXR decode refused: truncated header.');
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (view.getUint32(0, true) !== MAGIC) throw new Error('EXR decode refused: invalid magic.');
  if ((view.getUint32(4, true) & 0xff) !== 2) throw new Error('EXR decode refused: single-part scanline version 2 required.');
  let at = 8; const attrs = new Map<string, Uint8Array>();
  while (true) { const name = cstr(bytes, at); at += name.length + 1; if (!name) break; const type = cstr(bytes, at); at += type.length + 1; bound(bytes, at, 4); const size = view.getUint32(at, true); at += 4; bound(bytes, at, size); attrs.set(`${name}:${type}`, bytes.slice(at, at + size)); at += size; }
  const box = attrs.get('dataWindow:box2i'); const channels = attrs.get('channels:chlist'); const compression = attrs.get('compression:compression');
  if (!box || box.length !== 16 || !channels || !compression || ![0, 1, 2, 3].includes(compression[0])) throw new Error('EXR decode refused: requires NONE, RLE, ZIPS, or ZIP scanline channels and dataWindow.');
  const minX = new DataView(box.buffer, box.byteOffset, box.byteLength).getInt32(0, true), minY = new DataView(box.buffer, box.byteOffset, box.byteLength).getInt32(4, true), maxX = new DataView(box.buffer, box.byteOffset, box.byteLength).getInt32(8, true), maxY = new DataView(box.buffer, box.byteOffset, box.byteLength).getInt32(12, true);
  const width = maxX - minX + 1, height = maxY - minY + 1; if (width <= 0 || height <= 0 || width * height > MAX_PIXELS) throw new Error('EXR decode refused: invalid or oversized data window.');
  const parsed = parseChannels(channels); const byName = Object.fromEntries(parsed.map((channel) => [channel.name, channel])); if (!byName.R || !byName.G || !byName.B || parsed.some((channel) => !['R', 'G', 'B', 'A'].includes(channel.name)) || (byName.A && byName.A.type !== byName.R.type) || byName.R.type !== byName.G.type || byName.R.type !== byName.B.type) throw new Error('EXR decode refused: requires R, G, B[, A] channels of one HALF/FLOAT type; UINT and other layouts are refused.');
  const sampleBytes = byName.R.type === 1 ? 2 : 4, channelList = parsed.map((channel) => channel.name), rowBytes = width * sampleBytes * channelList.length, table = at; bound(bytes, table, height * 8); const data = new Float32Array(width * height * 4);
  const blockRows = compression[0] === 3 ? 16 : 1;
  for (let row = 0; row < height; row += blockRows) { const off = Number(view.getBigUint64(table + Math.floor(row / blockRows) * 8, true)); bound(bytes, off, 8); const y = view.getInt32(off, true) - minY, size = view.getUint32(off + 4, true), rows = Math.min(blockRows, height - y), expected = rowBytes * rows; bound(bytes, off + 8, size); if (y < 0 || y >= height) throw new Error('EXR decode refused: invalid scanline block.'); const raw = decodeExrBlock(bytes.slice(off + 8, off + 8 + size), compression[0], expected); let source = 0; for (let scan = 0; scan < rows; scan += 1) { for (const channel of channelList) for (let x = 0; x < width; x += 1) { const target = ((y + scan) * width + x) * 4 + ({ R: 0, G: 1, B: 2, A: 3 } as Record<string, number>)[channel]; data[target] = sampleBytes === 2 ? halfToFloat(new DataView(raw.buffer).getUint16(source, true)) : new DataView(raw.buffer).getFloat32(source, true); source += sampleBytes; } if (!byName.A) for (let x = 0; x < width; x += 1) data[((y + scan) * width + x) * 4 + 3] = 1; } }
  return { width, height, depth: sampleBytes === 2 ? 'f16' : 'f32', data };
}

export function encodeExr(raster: ExrRaster): Uint8Array {
  const { width, height, depth, data } = raster; if (!Number.isInteger(width) || !Number.isInteger(height) || width <= 0 || height <= 0 || width * height > MAX_PIXELS || data.length !== width * height * 4) throw new Error('EXR encode refused: invalid RGBA raster.');
  const type = depth === 'f16' ? 1 : 2, sampleBytes = depth === 'f16' ? 2 : 4, channel = channelAttribute(type), header = concat([attr('channels', 'chlist', channel), attr('compression', 'compression', new Uint8Array([0])), attr('dataWindow', 'box2i', box(width, height)), attr('displayWindow', 'box2i', box(width, height)), attr('lineOrder', 'lineOrder', new Uint8Array([0])), attr('pixelAspectRatio', 'float', f32(1)), attr('screenWindowCenter', 'v2f', concat([f32(0), f32(0)])), attr('screenWindowWidth', 'float', f32(1)), new Uint8Array([0])]);
  const tableAt = 8 + header.length, rowBytes = width * 4 * sampleBytes, first = tableAt + height * 8, out = new Uint8Array(first + height * (8 + rowBytes)), view = new DataView(out.buffer); view.setUint32(0, MAGIC, true); view.setUint32(4, 2, true); out.set(header, 8);
  let block = first; for (let y = 0; y < height; y += 1) { view.setBigUint64(tableAt + y * 8, BigInt(block), true); view.setInt32(block, y, true); view.setUint32(block + 4, rowBytes, true); let target = block + 8; for (let c = 0; c < 4; c += 1) for (let x = 0; x < width; x += 1) { const value = data[(y * width + x) * 4 + c]; if (depth === 'f16') view.setUint16(target, floatToHalf(value), true); else view.setFloat32(target, value, true); target += sampleBytes; } block += 8 + rowBytes; }
  return out;
}

function parseChannels(bytes: Uint8Array): Array<{ name: string; type: number }> { let at = 0; const out: Array<{ name: string; type: number }> = []; while (at < bytes.length) { const name = cstr(bytes, at); at += name.length + 1; if (!name) return out; bound(bytes, at, 16); const type = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getInt32(at, true); if ((type !== 1 && type !== 2) || bytes[at + 4] !== 0 || bytes[at + 5] !== 0 || bytes[at + 6] !== 0 || bytes[at + 7] !== 0 || out.some((channel) => channel.name === name)) throw new Error('EXR decode refused: unsupported, duplicate, UINT, or subsampled channel.'); out.push({ name, type }); at += 16; } throw new Error('EXR decode refused: unterminated channel list.'); }
function channelAttribute(type: number): Uint8Array { return concat(['R', 'G', 'B', 'A'].map((name) => concat([ascii(`${name}\0`), i32(type), new Uint8Array([0, 0, 0, 0]), i32(1), i32(1)])).concat(new Uint8Array([0]))); }
function attr(name: string, type: string, data: Uint8Array): Uint8Array { return concat([ascii(`${name}\0${type}\0`), i32(data.length), data]); }
function box(w: number, h: number): Uint8Array { return concat([i32(0), i32(0), i32(w - 1), i32(h - 1)]); }
function i32(n: number): Uint8Array { const out = new Uint8Array(4); new DataView(out.buffer).setInt32(0, n, true); return out; }
function f32(n: number): Uint8Array { const out = new Uint8Array(4); new DataView(out.buffer).setFloat32(0, n, true); return out; }
function ascii(value: string): Uint8Array { return new TextEncoder().encode(value); }
function cstr(bytes: Uint8Array, at: number): string { const end = bytes.indexOf(0, at); if (end < 0) throw new Error('EXR decode refused: unterminated header string.'); return new TextDecoder().decode(bytes.slice(at, end)); }
function bound(bytes: Uint8Array, at: number, n: number): void { if (!Number.isSafeInteger(at) || at < 0 || at + n > bytes.length) throw new Error('EXR decode refused: offset extends past end of file.'); }
function concat(parts: Uint8Array[]): Uint8Array { const size = parts.reduce((n, p) => n + p.length, 0), out = new Uint8Array(size); let at = 0; for (const part of parts) { out.set(part, at); at += part.length; } return out; }
function decodeExrBlock(block: Uint8Array, compression: number, expected: number): Uint8Array { if (compression === 0) { if (block.length !== expected) throw new Error('EXR decode refused: invalid NONE block size.'); return block; } const packed = compression === 1 ? exrRle(block, expected) : inflateZlibBounded(block, expected, 'EXR decode refused: compressed block length mismatch.'); if (packed.length !== expected) throw new Error('EXR decode refused: compressed block length mismatch.'); const predictor = packed.slice(); for (let i = 1; i < predictor.length; i += 1) predictor[i] = (predictor[i] + predictor[i - 1] - 128) & 255; const out = new Uint8Array(expected), half = Math.ceil(expected / 2); for (let i = 0; i < expected; i += 1) out[i] = predictor[(i % 2) * half + Math.floor(i / 2)]; return out; }
function exrRle(input: Uint8Array, expected: number): Uint8Array { const out = new Uint8Array(expected); let source = 0, target = 0; while (source < input.length && target < expected) { const count = (input[source++] << 24) >> 24; if (count < 0) { const n = -count; bound(input, source, n); if (target + n > expected) break; out.set(input.slice(source, source + n), target); source += n; target += n; } else { const n = count + 1, value = input[source++]; if (target + n > expected) break; out.fill(value, target, target + n); target += n; } } if (target !== expected) throw new Error('EXR decode refused: invalid RLE block.'); return out; }
function halfToFloat(h: number): number { const s = (h & 0x8000) ? -1 : 1, e = (h >>> 10) & 31, f = h & 1023; return e === 31 ? (f ? NaN : s * Infinity) : e === 0 ? s * 2 ** -14 * (f / 1024) : s * 2 ** (e - 15) * (1 + f / 1024); }
function floatToHalf(value: number): number { if (Number.isNaN(value)) return 0x7e00; const v = new Float32Array([value]), bits = new Uint32Array(v.buffer)[0], sign = (bits >>> 16) & 0x8000, exp = ((bits >>> 23) & 255) - 127 + 15, mantissa = bits & 0x7fffff; if (exp >= 31) return sign | (mantissa ? 0x7e00 : 0x7c00); if (exp <= 0) return exp < -10 ? sign : sign | ((mantissa | 0x800000) >>> (14 - exp)); return sign | (exp << 10) | (mantissa >>> 13); }
